# Generated by Django 3.2.3 on 2021-05-23 12:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_created',
            field=models.TimeField(auto_now_add='True', default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
