# Generated by Django 3.2.3 on 2021-06-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(blank='False', max_length=100, null='False'),
            preserve_default='False',
        ),
    ]
